
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: stitcher_fastapi
    image: stitcher_fastapi
    deploy:
      resources:
        limits:
          memory: 20g
    working_dir: /code
    volumes:
      - .:/code
      # - /Users/michaelawilson/repos/label-studio/mydata/stitchermedia:/media
      - /pool1/srv/label-studio/mydata/stitchermedia:/media
      - /pool1/srv/cvat-projects:/cvat_projects
      - sqlite_db:/sqlite_data
    env_file:
      - ./common.env
    command: fastapi run app/main.py --port 8090
    ports:
      - "8090:8090"

  redis:
    image: docker.io/redis:7.2
    container_name: stitcher_redis
    deploy:
      resources:
        limits:
          memory: 9g
    env_file:
      - ./common.env
    command: --port 6360
    ports:
      - "6360:6360"

  celery_worker:
    container_name: stitcher_worker
    image: stitcher_fastapi
    command: /start-celeryworker
    deploy:
      resources:
        limits:
          memory: 20g
    volumes:
      - .:/code
      # - /Users/michaelawilson/repos/label-studio/mydata/stitchermedia:/media
      - /pool1/srv/label-studio/mydata/stitchermedia:/media
      - /pool1/srv/cvat-projects:/cvat_projects
      - sqlite_db:/sqlite_data
    env_file:
      - ./common.env
    depends_on:
      - redis

  flower:
    container_name: stitcher_flower
    image: stitcher_fastapi
    command: /start-flower
    deploy:
      resources:
        limits:
          memory: 9g
    volumes:
      - .:/code
      # - /Users/michaelawilson/repos/label-studio/mydata/stitchermedia:/media
      - /pool1/srv/label-studio/mydata/stitchermedia:/media
      - /pool1/srv/cvat-projects:/cvat_projects
      - sqlite_db:/sqlite_data
    env_file:
      - ./common.env
    ports:
      - 5557:5555
    depends_on:
      - redis

volumes:
  sqlite_db:
