"""annotations

Revision ID: 098e492e4dfb
Revises: 8f0032eb73b1
Create Date: 2025-09-17 18:20:43.381353

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098e492e4dfb'
down_revision: Union[str, Sequence[str], None] = '8f0032eb73b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('annotator', sa.Integer(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('annotations_updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'annotations_updated_at')
    op.drop_column('uploadfilemodel', 'annotator')
    # ### end Alembic commands ###
