"""label_dir

Revision ID: 1d746a7671a4
Revises: 7773886c3352
Create Date: 2026-04-13 20:28:02.328957

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d746a7671a4'
down_revision: Union[str, Sequence[str], None] = '7773886c3352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('label_project_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('label_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('label_file_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'label_file_updated_at')
    op.drop_column('uploadfilemodel', 'label_file')
    op.drop_column('uploadfilemodel', 'label_project_dir')
    # ### end Alembic commands ###
