"""panorama_confidence

Revision ID: 228a8855e964
Revises: b9a68d02eca5
Create Date: 2025-08-29 15:03:02.589539

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228a8855e964'
down_revision: Union[str, Sequence[str], None] = 'b9a68d02eca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('panorama_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'panorama_confidence')
    # ### end Alembic commands ###
