"""label_job_id

Revision ID: 317641a433c0
Revises: 7d313e840ba0
Create Date: 2026-05-20 18:33:49.673848

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317641a433c0'
down_revision: Union[str, Sequence[str], None] = '7d313e840ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('label_job_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'label_job_id')
    # ### end Alembic commands ###
