"""segmentation

Revision ID: 47e9dde9b79c
Revises: d6218970d954
Create Date: 2025-11-20 15:44:09.516670

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e9dde9b79c'
down_revision: Union[str, Sequence[str], None] = 'd6218970d954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('predictions_coco', sa.JSON(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('predictions_timestamp_coco', sa.DateTime(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('label_studio_project', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('annotations_segment', sa.JSON(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('annotator_segment', sa.Integer(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('annotations_updated_at_segment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'annotations_updated_at_segment')
    op.drop_column('uploadfilemodel', 'annotator_segment')
    op.drop_column('uploadfilemodel', 'annotations_segment')
    op.drop_column('uploadfilemodel', 'label_studio_project')
    op.drop_column('uploadfilemodel', 'predictions_timestamp_coco')
    op.drop_column('uploadfilemodel', 'predictions_coco')
    # ### end Alembic commands ###
