"""label_file_rejected

Revision ID: 4f0d6e828478
Revises: 5c94a0cc838b
Create Date: 2026-08-25 17:07:01.012938

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0d6e828478'
down_revision: Union[str, Sequence[str], None] = '5c94a0cc838b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('label_file_rejected', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'label_file_rejected')
    # ### end Alembic commands ###
