"""omit_from_training

Revision ID: 55ce35ae2c3a
Revises: 8b3a871921b9
Create Date: 2026-01-22 20:08:15.513018

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ce35ae2c3a'
down_revision: Union[str, Sequence[str], None] = '8b3a871921b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('omit_from_training', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'omit_from_training')
    # ### end Alembic commands ###
