"""panorama_filenames

Revision ID: 585a0e74ff29
Revises: 4f0d6e828478
Create Date: 2026-08-27 18:22:39.438377

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585a0e74ff29'
down_revision: Union[str, Sequence[str], None] = '4f0d6e828478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('panorama_filenames', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'panorama_filenames')
    # ### end Alembic commands ###
