"""bugbox_rejected_str

Revision ID: 7773886c3352
Revises: 55ce35ae2c3a
Create Date: 2026-04-10 16:31:30.409166

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7773886c3352'
down_revision: Union[str, Sequence[str], None] = '55ce35ae2c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celerytask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_file_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('panorama_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starting_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exception', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finishing_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('uploadfilemodel', sa.Column('bugbox_rejected', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'bugbox_rejected')
    op.drop_table('celerytask')
    # ### end Alembic commands ###
