"""label

Revision ID: 7d313e840ba0
Revises: 1d746a7671a4
Create Date: 2026-04-14 19:47:04.227480

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d313e840ba0'
down_revision: Union[str, Sequence[str], None] = '1d746a7671a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('label_studio_project_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'label_studio_project_created_at')
    # ### end Alembic commands ###
