"""width

Revision ID: 826e5db0c3c4
Revises: 47e9dde9b79c
Create Date: 2025-11-20 20:25:51.980564

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826e5db0c3c4'
down_revision: Union[str, Sequence[str], None] = '47e9dde9b79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('panorama_width', sa.Integer(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('panorama_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'panorama_height')
    op.drop_column('uploadfilemodel', 'panorama_width')
    # ### end Alembic commands ###
