"""thumbnail

Revision ID: 8b3a871921b9
Revises: dfab2c5e8e27
Create Date: 2026-01-12 17:06:47.048391

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3a871921b9'
down_revision: Union[str, Sequence[str], None] = 'dfab2c5e8e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('panorama_thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_uploadfilemodel_panorama_thumbnail_path'), 'uploadfilemodel', ['panorama_thumbnail_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploadfilemodel_panorama_thumbnail_path'), table_name='uploadfilemodel')
    op.drop_column('uploadfilemodel', 'panorama_thumbnail_path')
    # ### end Alembic commands ###
