"""exceptionmessage,

Revision ID: b9a68d02eca5
Revises: 093f465141cf
Create Date: 2025-08-22 18:25:31.172639

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a68d02eca5'
down_revision: Union[str, Sequence[str], None] = '093f465141cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('stitching_exception', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('stitching_exception_at', sa.DateTime(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('panorma_timestamp', sa.DateTime(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'created_at')
    op.drop_column('uploadfilemodel', 'panorma_timestamp')
    op.drop_column('uploadfilemodel', 'stitching_exception_at')
    op.drop_column('uploadfilemodel', 'stitching_exception')
    # ### end Alembic commands ###
