"""bugbox_sample_id

Revision ID: d6218970d954
Revises: 098e492e4dfb
Create Date: 2025-09-26 19:47:04.548218

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6218970d954'
down_revision: Union[str, Sequence[str], None] = '098e492e4dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadfilemodel', sa.Column('bugbox_sample_id', sa.Integer(), nullable=True))
    op.add_column('uploadfilemodel', sa.Column('bugbox_croped_saved', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadfilemodel', 'bugbox_croped_saved')
    op.drop_column('uploadfilemodel', 'bugbox_sample_id')
    # ### end Alembic commands ###
