MEDIA_PATH = '/media'
CVAT_PROJECTS_PATH = '/cvat_projects'
ERROR_MSG_KEY = 'ERROR'

IMAGES_PREFIX = 'image_r'  # images for stiching must include this prefix
STITCHER_LABEL_IMG = 'label_r_001.jpg'  # the expected label image
STITCHER_LABEL_THUMB_IMG = 'label_r_001_thumbnail.jpg'

PANO_NAME_BASE = 'panorama'
PANO_EXTENSION = '.jpg'
PANO_NAME_SEPERATOR = '__'

DEFAULT_CONFIDENCE_LEVEL = 0.9

LABEL_STUDIO_FILTER_DESC = 'When True, filters where panorama is approved'

INDEX_DATATABLES_SEARCH = 'search[value]'
INDEX_DATATABLES_LSPROJECT = 'lsproject'
INDEX_DATATABLES_NEEDS_LINKED = 'needs_linked'
INDEX_DATATABLES_SAMPLE_LINKED = 'sample_linked'
INDEX_DATATABLES_NOTA_SAMPLE = 'nota_sample'
INDEX_DATATABLES_UNREVIEWED = 'unreviewed'
INDEX_DATATABLES_APPROVED = 'approved'
INDEX_DATATABLES_DISAPPROVED = 'disapproved'
INDEX_DATATABLES_LABEL_UPDATED = 'label_updated'
INDEX_DATATABLES_ANNOTATIONS = 'annotations'
INDEX_DATATABLES_NOT_COMPLETED = 'not_completed'
INDEX_DATATABLES_COMPLETED = 'completed'
INDEX_DATATABLES_REJECTED = 'rejected'
INDEX_DATATABLES_DRAW = 'draw'
INDEX_DATATABLES_HAS_DUPLICATE = 'has_duplicate'

INDEX_DATATABLES_PARAMS = (
    INDEX_DATATABLES_SEARCH,
    INDEX_DATATABLES_LSPROJECT,
    INDEX_DATATABLES_NEEDS_LINKED,
    INDEX_DATATABLES_SAMPLE_LINKED,
    INDEX_DATATABLES_NOTA_SAMPLE,
    INDEX_DATATABLES_UNREVIEWED,
    INDEX_DATATABLES_APPROVED,
    INDEX_DATATABLES_DISAPPROVED,
    INDEX_DATATABLES_LABEL_UPDATED,
    INDEX_DATATABLES_ANNOTATIONS,
    INDEX_DATATABLES_NOT_COMPLETED,
    INDEX_DATATABLES_COMPLETED,
    INDEX_DATATABLES_REJECTED,
    INDEX_DATATABLES_DRAW,
    INDEX_DATATABLES_HAS_DUPLICATE
)
